name: prueba_ceiba_flutter
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.1
  hive_flutter: ^1.1.0


  cupertino_icons: ^1.0.2
  http: ^0.13.3
  build_runner: ^2.1.2

dev_dependencies:
  hive_generator: ^1.1.3
  mocktail: ^0.3.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true